import type { Topic } from '@cigbuddy/shared';

/**
 * Conversation topics, one shown per room. The catalogue is canonical: the
 * `topics` table is seeded from it at boot, so adding or rewording one is a
 * code change reviewed in a diff like everything else. An operator can still
 * retire a row in the database without a deploy -- see `topics.source`.
 *
 * Voice: the slogans' voice, asked as a question. Lowercase throughout, dry,
 * specific, no exclamation marks, no "let's get to know each other", no
 * therapy-speak, and no question that only works if both people are having a
 * nice day. `catalog.test.ts` enforces the mechanical half of that.
 *
 * On `divisive`. These are meant to be genuinely contested -- politics,
 * religion, money, the moral flashpoints -- because a stranger you will never
 * meet again is the one person you can actually argue with. The line is that
 * every one of them is a question two people can answer opposite ways in good
 * faith. A prompt that attacks people for what they are is not a conversation
 * starter, it is the thing the report button exists to catch, and it would be
 * this site handing out the reason to press it. Argue about the world, never
 * about the person on the other camera.
 *
 * Keys are stable and never reused: reword `text`, keep `t-042`.
 */
export const TOPIC_CATALOG = [
  // ---- openers -------------------------------------------------------------
  { id: 't-001', kind: 'opener', text: "what's the worst job you were good at" },
  { id: 't-002', kind: 'opener', text: 'what did you believe for far too long' },
  { id: 't-003', kind: 'opener', text: 'who taught you to smoke, and are they still around' },
  { id: 't-004', kind: 'opener', text: "what's in your pockets right now" },
  { id: 't-005', kind: 'opener', text: 'what did your childhood bedroom smell like' },
  { id: 't-006', kind: 'opener', text: "what's the most money you've spent on something stupid" },
  { id: 't-007', kind: 'opener', text: 'when did you last sit outside doing nothing on purpose' },
  { id: 't-008', kind: 'opener', text: "what's a skill you have that has never once been useful" },
  {
    id: 't-009',
    kind: 'opener',
    text: "what's the last thing you looked up and forgot immediately",
  },
  { id: 't-010', kind: 'opener', text: 'what did you have for breakfast, and was it a mistake' },
  { id: 't-011', kind: 'opener', text: "what's the worst advice you actually took" },
  { id: 't-012', kind: 'opener', text: "what's the last thing you googled. no editing" },
  { id: 't-013', kind: 'opener', text: "what's the oldest thing you own that still works" },
  { id: 't-014', kind: 'opener', text: 'who was your first proper friend and where did they go' },
  { id: 't-015', kind: 'opener', text: "what's the longest you've gone without sleep, and why" },
  { id: 't-016', kind: 'opener', text: 'what song do you know every word of against your will' },
  { id: 't-017', kind: 'opener', text: "what's the furthest you've walked because of a mistake" },
  { id: 't-018', kind: 'opener', text: 'what did you want to be at nine' },
  { id: 't-019', kind: 'opener', text: "what's the worst haircut you've paid for" },
  { id: 't-020', kind: 'opener', text: 'what last made you laugh out loud on your own' },
  { id: 't-021', kind: 'opener', text: "what's the strangest job you've been offered" },
  { id: 't-022', kind: 'opener', text: "what do you do when you can't sleep" },
  { id: 't-023', kind: 'opener', text: "what's something everyone in your family says" },
  { id: 't-024', kind: 'opener', text: "what's your most useless piece of trivia" },
  { id: 't-025', kind: 'opener', text: 'what did you last throw away and regret' },
  { id: 't-026', kind: 'opener', text: 'where were you living five years ago' },
  { id: 't-027', kind: 'opener', text: "what's the worst thing you've eaten to be polite" },
  { id: 't-028', kind: 'opener', text: "what's a place you've been to once and never again" },
  { id: 't-029', kind: 'opener', text: "what's the smallest thing that ruins your day" },
  // Not "how did you get that scar": on a video call that points at the other
  // person's body and assumes an answer they may not want to give.
  { id: 't-030', kind: 'opener', text: "what's the worst injury you've done to yourself" },
  { id: 't-031', kind: 'opener', text: "what's the last photo on your phone" },
  {
    id: 't-032',
    kind: 'opener',
    text: "what's the most hours you've put into something nobody saw",
  },
  { id: 't-033', kind: 'opener', text: "what's a word you've been mispronouncing your whole life" },
  { id: 't-034', kind: 'opener', text: 'what was the last thing you finished' },
  { id: 't-035', kind: 'opener', text: 'what do you own too many of' },
  { id: 't-036', kind: 'opener', text: "what's the best thing you've found on the street" },
  {
    id: 't-037',
    kind: 'opener',
    text: 'who in your life would be hardest to explain to a stranger',
  },
  { id: 't-038', kind: 'opener', text: "what's a rule in your house that made no sense" },
  { id: 't-039', kind: 'opener', text: "what's the worst weather you've stood outside in" },
  { id: 't-040', kind: 'opener', text: 'what did you lie about on a form' },
  { id: 't-041', kind: 'opener', text: "what's the last thing you made with your hands" },
  { id: 't-042', kind: 'opener', text: 'who do you owe money to, roughly' },
  { id: 't-043', kind: 'opener', text: "what's your least favourite sound" },
  { id: 't-044', kind: 'opener', text: 'what were you doing this time last year' },
  { id: 't-045', kind: 'opener', text: "what's the last thing you quit" },
  { id: 't-046', kind: 'opener', text: "what's the nicest thing a stranger has done for you" },
  { id: 't-047', kind: 'opener', text: "what's the closest you've come to being arrested" },
  { id: 't-048', kind: 'opener', text: "what's the worst gift you've given" },
  { id: 't-049', kind: 'opener', text: 'what do you always forget to buy' },
  { id: 't-050', kind: 'opener', text: "what's the last thing you cried at, film or otherwise" },
  { id: 't-051', kind: 'opener', text: "what's the most useless thing you're proud of" },
  { id: 't-052', kind: 'opener', text: "what's your relationship with mornings" },
  { id: 't-053', kind: 'opener', text: "what's something you're bad at that you keep doing" },
  { id: 't-054', kind: 'opener', text: 'what did you last argue with a machine about' },
  { id: 't-055', kind: 'opener', text: "what's the longest you've kept a plant alive" },
  { id: 't-056', kind: 'opener', text: "what's the worst holiday you've been on" },
  { id: 't-057', kind: 'opener', text: 'who taught you to cook, if anyone' },
  { id: 't-058', kind: 'opener', text: "what's the last thing you fixed instead of replacing" },
  { id: 't-059', kind: 'opener', text: "what's a smell that puts you somewhere immediately" },
  { id: 't-060', kind: 'opener', text: "what's the most people you've ever lied to at once" },

  // ---- would you rather ----------------------------------------------------
  { id: 't-061', kind: 'wyr', text: 'would you rather always be slightly cold or slightly damp' },
  { id: 't-062', kind: 'wyr', text: 'would you rather know when you die or how' },
  { id: 't-063', kind: 'wyr', text: 'would you rather lose every photo or every message' },
  {
    id: 't-064',
    kind: 'wyr',
    text: 'would you rather be famous for something bad or unknown for something good',
  },
  { id: 't-065', kind: 'wyr', text: 'would you rather never be early or never be on time' },
  {
    id: 't-066',
    kind: 'wyr',
    text: 'would you rather read minds or have nobody able to read yours',
  },
  {
    id: 't-067',
    kind: 'wyr',
    text: 'would you rather have one long life alone or a short one crowded',
  },
  {
    id: 't-068',
    kind: 'wyr',
    text: 'would you rather be permanently overdressed or permanently underdressed',
  },
  {
    id: 't-069',
    kind: 'wyr',
    text: 'would you rather lose your sense of taste or your sense of smell',
  },
  { id: 't-070', kind: 'wyr', text: 'would you rather live somewhere too loud or too quiet' },
  {
    id: 't-071',
    kind: 'wyr',
    text: 'would you rather be the cleverest person in the room forever or the funniest',
  },
  { id: 't-072', kind: 'wyr', text: 'would you rather have no past or no future' },
  {
    id: 't-073',
    kind: 'wyr',
    text: 'would you rather work twice as hard for half as long, or the reverse',
  },
  {
    id: 't-074',
    kind: 'wyr',
    text: 'would you rather everyone hear your thoughts one day a year, or nobody ever',
  },
  { id: 't-075', kind: 'wyr', text: 'would you rather never be bored or never be tired' },
  {
    id: 't-076',
    kind: 'wyr',
    text: 'would you rather have every conversation recorded or none remembered',
  },
  { id: 't-077', kind: 'wyr', text: "would you rather always know you're being lied to, or never" },
  {
    id: 't-078',
    kind: 'wyr',
    text: 'would you rather your first love or your last see how you turned out',
  },
  {
    id: 't-079',
    kind: 'wyr',
    text: 'would you rather be forgotten entirely or remembered wrongly',
  },
  { id: 't-080', kind: 'wyr', text: 'would you rather have money now or time later' },
  {
    id: 't-081',
    kind: 'wyr',
    text: 'would you rather lose ten years off the end or five from the middle',
  },
  {
    id: 't-082',
    kind: 'wyr',
    text: 'would you rather be feared by strangers or pitied by friends',
  },
  { id: 't-083', kind: 'wyr', text: 'would you rather live without music or without any story' },
  {
    id: 't-084',
    kind: 'wyr',
    text: 'would you rather have the perfect answer too late, or a rough one now',
  },
  {
    id: 't-085',
    kind: 'wyr',
    text: 'would you rather never leave your country or never return to it',
  },
  { id: 't-086', kind: 'wyr', text: 'would you rather be interrupted constantly or ignored' },
  { id: 't-087', kind: 'wyr', text: 'would you rather own nothing or owe everything' },
  { id: 't-088', kind: 'wyr', text: 'would you rather your worst day or your best be public' },
  { id: 't-089', kind: 'wyr', text: 'would you rather age only in your face or only in your body' },
  {
    id: 't-090',
    kind: 'wyr',
    text: 'would you rather have one true friend or a hundred useful ones',
  },
  {
    id: 't-091',
    kind: 'wyr',
    text: 'would you rather always sweat slightly or always have cold hands',
  },
  { id: 't-092', kind: 'wyr', text: 'would you rather redo one year or skip one' },
  { id: 't-093', kind: 'wyr', text: 'would you rather never sit down or never lie down' },
  {
    id: 't-094',
    kind: 'wyr',
    text: 'would you rather be a spare part in a good life or the lead in a dull one',
  },
  {
    id: 't-095',
    kind: 'wyr',
    text: "would you rather know everyone's secret or have nobody know yours",
  },

  // ---- small opinions ------------------------------------------------------
  { id: 't-096', kind: 'take', text: 'cereal is soup and you know it' },
  { id: 't-097', kind: 'take', text: 'breakfast is not the most important meal of anything' },
  { id: 't-098', kind: 'take', text: 'nobody actually likes the beach' },
  { id: 't-099', kind: 'take', text: 'most films should be ninety minutes' },
  {
    id: 't-100',
    kind: 'take',
    text: "you don't have a favourite book, you have a book you mention",
  },
  { id: 't-101', kind: 'take', text: 'the countryside is loud' },
  { id: 't-102', kind: 'take', text: "people who don't take sugar are showing off" },
  { id: 't-103', kind: 'take', text: 'everyone is pretending to like jazz' },
  { id: 't-104', kind: 'take', text: 'birthdays should stop at thirty' },
  { id: 't-105', kind: 'take', text: 'queueing is the highest form of civilisation' },
  { id: 't-106', kind: 'take', text: 'every restaurant is too dark now' },
  { id: 't-107', kind: 'take', text: 'the five-second rule is real and you follow it' },
  {
    id: 't-108',
    kind: 'take',
    text: 'small talk is a skill and people who dismiss it are bad at it',
  },
  { id: 't-109', kind: 'take', text: 'nobody has ever enjoyed a surprise party' },
  { id: 't-110', kind: 'take', text: 'voice notes are a hostile act' },
  { id: 't-111', kind: 'take', text: 'tipping culture is a scam everyone agreed to' },
  { id: 't-112', kind: 'take', text: 'sandwiches taste better cut diagonally and that is physics' },
  { id: 't-113', kind: 'take', text: 'the second season is always the good one' },
  { id: 't-114', kind: 'take', text: "nobody reads the terms and that's the company's fault" },
  { id: 't-115', kind: 'take', text: 'driving is too easy to be legal' },
  { id: 't-116', kind: 'take', text: 'lifts should not have mirrors' },
  { id: 't-117', kind: 'take', text: 'every wedding is too long' },
  { id: 't-118', kind: 'take', text: 'camping is just being poor on purpose' },
  { id: 't-119', kind: 'take', text: 'the book is not always better' },
  { id: 't-120', kind: 'take', text: 'people who describe themselves as blunt are just rude' },
  { id: 't-121', kind: 'take', text: 'white walls are cowardice' },
  { id: 't-122', kind: 'take', text: 'all airports are the same airport' },
  { id: 't-123', kind: 'take', text: 'there is no good reason to run' },
  { id: 't-124', kind: 'take', text: 'cold weather is better than hot and this is not debatable' },
  { id: 't-125', kind: 'take', text: "nobody's dog is that friendly" },
  { id: 't-126', kind: 'take', text: 'the office was better before it was optional' },
  { id: 't-127', kind: 'take', text: 'everyone secretly likes their own cooking best' },
  { id: 't-128', kind: 'take', text: 'resolutions in january are a tax on optimism' },
  { id: 't-129', kind: 'take', text: 'every photo of food is the same photo' },
  { id: 't-130', kind: 'take', text: "people don't change, they just get tired" },
  { id: 't-131', kind: 'take', text: 'no adult needs a straw' },
  { id: 't-132', kind: 'take', text: 'paper maps were better and we gave up too fast' },
  { id: 't-133', kind: 'take', text: 'being on time is a personality, not a virtue' },
  { id: 't-134', kind: 'take', text: 'the best part of any holiday is the last night' },
  {
    id: 't-135',
    kind: 'take',
    text: 'every group has a person who books things, and it should be you',
  },

  // ---- confessions ---------------------------------------------------------
  { id: 't-136', kind: 'confession', text: "what's the last thing you lied about" },
  { id: 't-137', kind: 'confession', text: "the pettiest reason you've ended something" },
  { id: 't-138', kind: 'confession', text: 'what have you stolen, and did it count' },
  { id: 't-139', kind: 'confession', text: "what's the worst thing you've said out loud" },
  { id: 't-140', kind: 'confession', text: 'what do you pretend to have read' },
  { id: 't-141', kind: 'confession', text: 'who have you been avoiding, and for how long' },
  { id: 't-142', kind: 'confession', text: "what's the most embarrassing thing you've googled" },
  { id: 't-143', kind: 'confession', text: "what have you thrown away that wasn't yours" },
  { id: 't-144', kind: 'confession', text: "what's a rumour about you that was true" },
  { id: 't-145', kind: 'confession', text: "what do you do that you'd never admit to a housemate" },
  { id: 't-146', kind: 'confession', text: 'who did you let take the blame' },
  { id: 't-147', kind: 'confession', text: "what's the longest you've held a grudge over nothing" },
  { id: 't-148', kind: 'confession', text: 'what have you never given back' },
  { id: 't-149', kind: 'confession', text: "what's something you're glad nobody filmed" },
  { id: 't-150', kind: 'confession', text: 'what did you break and blame on someone else' },
  { id: 't-151', kind: 'confession', text: 'what do you judge people for while doing it yourself' },
  {
    id: 't-152',
    kind: 'confession',
    text: "what's the worst excuse you've used and got away with",
  },
  { id: 't-153', kind: 'confession', text: 'who have you unfollowed out of spite' },
  { id: 't-154', kind: 'confession', text: 'what have you faked being good at' },
  // Not "the meanest thing you've thought about a stranger": asked of two
  // strangers looking at each other, that is an invitation, not a confession.
  { id: 't-155', kind: 'confession', text: 'what were you last unfairly annoyed about' },
  { id: 't-156', kind: 'confession', text: 'what did you cheat at and still feel fine about' },
  { id: 't-157', kind: 'confession', text: "who's a friend you keep for exactly one reason" },
  { id: 't-158', kind: 'confession', text: "what have you cried about that wasn't worth it" },
  { id: 't-159', kind: 'confession', text: 'what do you spend money on that you hide' },
  { id: 't-160', kind: 'confession', text: "what's the last promise you broke" },
  {
    id: 't-161',
    kind: 'confession',
    text: 'what would your search history get you in trouble for',
  },
  { id: 't-162', kind: 'confession', text: 'who have you ghosted, and did they deserve it' },
  { id: 't-163', kind: 'confession', text: 'what have you never told anyone about a job' },
  { id: 't-164', kind: 'confession', text: "what's the pettiest thing you've done for revenge" },
  { id: 't-165', kind: 'confession', text: 'what do you still feel bad about from school' },

  // ---- hypotheticals -------------------------------------------------------
  { id: 't-166', kind: 'hypothetical', text: 'one do-over, any year. which one' },
  { id: 't-167', kind: 'hypothetical', text: 'you can uninvent one thing. go' },
  { id: 't-168', kind: 'hypothetical', text: 'you get one sentence to your ten-year-old self' },
  {
    id: 't-169',
    kind: 'hypothetical',
    text: 'you have to live in an airport for a year. how do you do it',
  },
  { id: 't-170', kind: 'hypothetical', text: 'you can delete one month from your memory. which' },
  {
    id: 't-171',
    kind: 'hypothetical',
    text: "you get everyone's attention for sixty seconds. what do you say",
  },
  {
    id: 't-172',
    kind: 'hypothetical',
    text: "a stranger leaves you a house in a country you've never been to. do you go",
  },
  { id: 't-173', kind: 'hypothetical', text: 'you can never lie again. what breaks first' },
  { id: 't-174', kind: 'hypothetical', text: 'you wake up fluent in one language. which, and why' },
  {
    id: 't-175',
    kind: 'hypothetical',
    text: "you have to speak at a stranger's funeral. what's it about",
  },
  { id: 't-176', kind: 'hypothetical', text: 'you can send one message to one day in the past' },
  {
    id: 't-177',
    kind: 'hypothetical',
    text: 'everyone has to wear their job on their chest. better or worse',
  },
  {
    id: 't-178',
    kind: 'hypothetical',
    text: 'you get one skill overnight but forget one you have. trade',
  },
  {
    id: 't-179',
    kind: 'hypothetical',
    text: 'you can stop time, but can never tell anyone. what do you actually do',
  },
  { id: 't-180', kind: 'hypothetical', text: "you move tomorrow, one bag. what's in it" },
  {
    id: 't-181',
    kind: 'hypothetical',
    text: 'you find out the last ten years were a test. do you want the score',
  },
  { id: 't-182', kind: 'hypothetical', text: 'you can make one law that nobody can ever repeal' },
  {
    id: 't-183',
    kind: 'hypothetical',
    text: 'everyone forgets your name but remembers you. survivable',
  },
  {
    id: 't-184',
    kind: 'hypothetical',
    text: "you get to read one person's diary, no consequences. whose",
  },
  {
    id: 't-185',
    kind: 'hypothetical',
    text: 'you have to pick a decade to live the rest of your life in',
  },
  { id: 't-186', kind: 'hypothetical', text: 'you can be excellent at one thing or good at ten' },
  {
    id: 't-187',
    kind: 'hypothetical',
    text: 'you are told exactly how long you have. who do you tell',
  },
  { id: 't-188', kind: 'hypothetical', text: 'you can remove one emotion permanently' },
  {
    id: 't-189',
    kind: 'hypothetical',
    text: 'you get a building. any building. what happens to it',
  },
  {
    id: 't-190',
    kind: 'hypothetical',
    text: "everyone you've met votes on one decision of yours. which do you hand over",
  },
  {
    id: 't-191',
    kind: 'hypothetical',
    text: 'one hour of your life plays publicly, your choice. which hour',
  },
  {
    id: 't-192',
    kind: 'hypothetical',
    text: "you wake up as someone you know for a week. who's the most useful",
  },
  {
    id: 't-193',
    kind: 'hypothetical',
    text: 'you can keep one year of your life exactly, forever',
  },
  {
    id: 't-194',
    kind: 'hypothetical',
    text: "you get told the one thing people don't say to you. do you listen",
  },
  {
    id: 't-195',
    kind: 'hypothetical',
    text: 'money stops existing tomorrow. what do you do on the first day',
  },

  // ---- real arguments ------------------------------------------------------
  // Contested on purpose. See the note at the top of this file for the line.
  { id: 't-196', kind: 'divisive', text: 'should voting be compulsory' },
  { id: 't-197', kind: 'divisive', text: 'inherited wealth should be taxed to nothing' },
  { id: 't-198', kind: 'divisive', text: 'has religion done more good than harm' },
  { id: 't-199', kind: 'divisive', text: 'assisted dying should be legal everywhere' },
  { id: 't-200', kind: 'divisive', text: 'nobody should be allowed to own a billion' },
  { id: 't-201', kind: 'divisive', text: 'open borders. honestly' },
  { id: 't-202', kind: 'divisive', text: 'the death penalty is never justified' },
  { id: 't-203', kind: 'divisive', text: 'all drugs should be legal' },
  { id: 't-204', kind: 'divisive', text: 'private schools should not exist' },
  { id: 't-205', kind: 'divisive', text: "is patriotism just luck you're proud of" },
  { id: 't-206', kind: 'divisive', text: 'free speech has to include speech you find disgusting' },
  { id: 't-207', kind: 'divisive', text: 'monarchy is a tourist attraction with a pension' },
  { id: 't-208', kind: 'divisive', text: 'prison should be rehabilitation only, never punishment' },
  {
    id: 't-209',
    kind: 'divisive',
    text: 'is there a moral difference between eating a pig and a dog',
  },
  { id: 't-210', kind: 'divisive', text: 'should the rich be able to buy better healthcare' },
  { id: 't-211', kind: 'divisive', text: 'countries should pay reparations for what they did' },
  { id: 't-212', kind: 'divisive', text: "is there a god, and would it change how you'd live" },
  { id: 't-213', kind: 'divisive', text: 'should parents raise children in a religion' },
  { id: 't-214', kind: 'divisive', text: 'the voting age should be sixteen' },
  { id: 't-215', kind: 'divisive', text: 'war is sometimes the right answer' },
  { id: 't-216', kind: 'divisive', text: 'should anyone be allowed to fund an election' },
  { id: 't-217', kind: 'divisive', text: 'the internet was a mistake' },
  { id: 't-218', kind: 'divisive', text: 'should we go to mars while this one is on fire' },
  { id: 't-219', kind: 'divisive', text: 'is it wrong to have children right now' },
  { id: 't-220', kind: 'divisive', text: 'are the big museums holding stolen goods' },
  { id: 't-221', kind: 'divisive', text: 'should the state ever be able to search your phone' },
  { id: 't-222', kind: 'divisive', text: 'has nationalism ever produced anything good' },
  { id: 't-223', kind: 'divisive', text: 'should juries be replaced by people who know the law' },
  { id: 't-224', kind: 'divisive', text: 'is capitalism reformable, or is that the joke' },
  { id: 't-225', kind: 'divisive', text: 'social media should be age-restricted like alcohol' },
  { id: 't-226', kind: 'divisive', text: 'is charity a way of dodging tax and guilt at once' },
  { id: 't-227', kind: 'divisive', text: 'can a country ever be right to refuse refugees' },
  { id: 't-228', kind: 'divisive', text: 'is cancel culture accountability or a mob' },
  { id: 't-229', kind: 'divisive', text: 'should we eat meat at all' },
  { id: 't-230', kind: 'divisive', text: "are protests worth anything if they're legal" },
  { id: 't-231', kind: 'divisive', text: 'should the police be armed' },
  { id: 't-232', kind: 'divisive', text: 'is it moral to work for a company you think is harmful' },
  { id: 't-233', kind: 'divisive', text: 'there should be a maximum wage as well as a minimum' },
  { id: 't-234', kind: 'divisive', text: 'is the nuclear bomb ever defensible' },
  { id: 't-235', kind: 'divisive', text: 'should religious institutions pay tax' },
  { id: 't-236', kind: 'divisive', text: 'is a nationalised industry better than a competing one' },
  { id: 't-237', kind: 'divisive', text: 'should we bring back extinct animals' },
  { id: 't-238', kind: 'divisive', text: 'does anybody deserve what they have' },
  { id: 't-239', kind: 'divisive', text: 'is it ever right to break a law you think is unjust' },
  {
    id: 't-240',
    kind: 'divisive',
    text: 'should a machine ever make a legal decision about a person',
  },
] as const satisfies readonly Topic[];
